# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

docs: |
  Applications represent the credit application for a borrower. 
  Applications must be created for a given borrower, and one borrower can have many applications. 
  Once an application is created, it must either be approved or rejected.
  Creating a borrower (or referencing an existing one) is the first step in the Pier credit origination process.

imports:
  commons: commons.yml
  borrowers: borrowers.yml

service:
  base-path: /applications
  auth: true
  endpoints:
    create:
      display-name: Create an application
      path: ""
      method: POST
      request:
        name: CreateApplicationRequest
        body:
          properties:
            borrower_id:
              type: string
              docs: The `borrower_id` of the borrower the application is for (1-256 chars)
            credit_type:
              type: commons.CreditType
              docs: The type of credit product.
            requested_amount:
              type: optional<integer>
              docs:
                If the borrower requests an amount in their application, the requested
                loan or credit line amount (in cents).
            third_party_disbursement_destination:
              type: optional<string>
              docs: For credit applications of type `consumer_bnpl`, the third party (i.e. merchant) receiving the funds is
      response: Application
      errors:
        - commons.InvalidInputError
        - commons.BorrowerNotFoundError
      examples:
        - request:
            borrower_id: $borrowers.ConsumerBorrowerId.Default
            credit_type: consumer_installment_loan
            requested_amount: 200000
          response:
            body: $Application.PendingApplication

    approve:
      display-name: Approve an application
      path: /{application_id}/approve
      path-parameters:
        application_id: ApplicationId
      method: POST
      request: list<Offer>
      response: Application
      errors:
        - commons.InvalidInputError
        - commons.BorrowerNotFoundError
      examples:
        - path-parameters:
            application_id: $ApplicationId.Example0
          request:
            - $Offer.Loan
          response:
            body: $Application.ApprovedApplication

    reject:
      display-name: Reject an application
      docs:
        Updates the status of a credit application to `rejected` and returns a
        user readable rejection reason, to be used in the adverse action notice
      path: /{application_id}/reject
      path-parameters:
        application_id: ApplicationId
      method: POST
      request:
        name: Reject
        body:
          properties:
            rejection_reasons: list<RejectionReason>
      response: Application
      errors:
        - commons.InvalidInputError
        - commons.ApplicationNotFoundError
      examples:
        - path-parameters:
            application_id: $ApplicationId.Example0
          request:
            rejection_reasons: [bank_balance_too_low]
          response:
            body: $Application.RejectedApplication

    get:
      display-name: Get an application by ID
      docs: Get an application by its id
      path: /{application_id}
      path-parameters:
        application_id: ApplicationId
      method: GET
      response: Application
      errors:
        - commons.ApplicationNotFoundError
        - commons.InvalidApplicationIdError
      examples:
        - path-parameters:
            application_id: $ApplicationId.Example0
          response:
            body: $Application.ApprovedApplication

    getAll:
      display-name: List all applications
      docs: List all applications associated with your account
      path: ""
      method: GET
      response: list<Application>
      examples:
        - response:
            body:
              - $Application.ApprovedApplication
              - $Application.PendingApplication

types:
  ApplicationId:
    type: string
    examples:
      - name: Example0
        value: app_f0467657bba948e6a87292e182132848

  ApplicationStatus:
    enum:
      - value: pending
        docs: the application is pending a decision
      - value: approved
        docs: the application is approved with an offer
      - value: accepted
        docs: the application offer has been accepted by the borrower
      - value: declined
        docs: the application is declined
      - value: incomplete
        docs: the application is incomplete
      - value: rejected
        docs: the application is rejected

  Offer:
    union:
      revolving_line_of_credit_offer: LineOfCreditOffer
      loan_offer: LoanOffer
      merchant_advance_offer: MerchantAdvanceOfferSchema
    examples:
      - name: LineOfCredit
        value:
          type: revolving_line_of_credit_offer
          amount: 1000000
          apr: 0
          annual_fee: 0
          billing_cycle: 30
          finance_charge: 0
          grace_period:
            term: 21
            interest_rate: 0
          interest_rate: 0
          late_payment_fee: 0
          origination_fee: 0
          minimum_payment:
            type: interest_plus_percentage_of_principal
            value: 500
      - name: Loan
        value:
          type: loan_offer
          amount: 1000000
          grace_period:
            term: 0
            interest_rate: 0
          interest_rate: 0
          origination_fee: 0
          payment_period: monthly
          late_payment_fee: 0
          first_payment_date: "2022-12-31"
          term:
            term_type: "months"
            term: 36
      - name: SecuredLoan
        value:
          type: loan_offer
          amount: 1000000
          grace_period:
            term: 0
            interest_rate: 0
          interest_rate: 0
          origination_fee: 0
          payment_period: monthly
          late_payment_fee: 0
          first_payment_date: "2022-12-31"
          term:
            term_type: "months"
            term: 36
          security_amount: 10000
      - name: MerchantAdvanceOfferSchema
        value:
          type: merchant_advance_offer
          amount: 1000000
          factor_rate: 150
          payment_period: monthly
          origination_fee: 0
          late_payment_fee: 0
          receivables_portion: 1500
          minimum_payment: 500
          maximum_payment: 5000

  Application:
    properties:
      id: optional<ApplicationId>
      borrower_id:
        type: optional<borrowers.ConsumerBorrowerId>
        docs: The `borrower_id` of the borrower the application belongs to
      created_on:
        type: optional<datetime>
        docs: Timestamp the application object is created on
      credit_type:
        type: optional<commons.CreditType>
        docs: The type of credit product.
      decisioned_on:
        type: optional<datetime>
        docs: Timestamp when the application is either approved or rejected on
      offers:
        type: optional<list<Offer>>
        docs:
          If the application is approved, an object containing the credit offer
          details
      rejection_reasons:
        type: optional<list<RejectionReason>>
        docs: >
          If the application is rejected, a list containing 1-4 rejection
          reason(s).  The Rejection Reasons endpoint provides a list of valid
          reasons and descriptors
      requested_amount:
        type: optional<integer>
        docs: >
          If the borrower requests an amount in their application, the
          requested  loan or credit line amount in cents (e.g. 500000 for
          $5,000)
      status: ApplicationStatus
      third_party_disbursement_destination:
        type: optional<string>
        docs:
          For credit applications of type `consumer_bnpl`, the third party (i.e. merchant) receiving the funds is
          specified here
      lender_of_record:
        type: optional<string>
        docs: The lender of record
      credit_data: optional<CreditData>
    examples:
      - name: PendingApplication
        value:
          id: $ApplicationId.Example0
          borrower_id: $borrowers.ConsumerBorrowerId.Default
          credit_type: consumer_installment_loan
          rejection_reasons: []
          status: pending
          lender_of_record: lender
          created_on: "2022-12-31T01:36:52.606Z"
      - name: ApprovedApplication
        value:
          id: $ApplicationId.Example0
          borrower_id: bor_d965bea9f47a4b108562642dbb1dae9f
          credit_type: consumer_revolving_line_of_credit
          rejection_reasons: []
          status: approved
          offers: [ $Offer.LineOfCredit ]
          lender_of_record: lender
          created_on: "2022-12-31T01:36:52.606Z"
          decisioned_on: "2023-01-17T05:31:52.955Z"
      - name: RejectedApplication
        value:
          rejection_reasons:
            - bank_balance_too_low
          id: $ApplicationId.Example0
          borrower_id: bor_1677bbbaf21a4954bb114bd9c4348d8a
          credit_type: consumer_installment_loan
          status: rejected
          lender_of_record: lender
          created_on: "2022-12-31T02:20:35.934Z"
          decisioned_on: "2022-12-31T02:21:01.842Z"

  LineOfCreditOffer:
    properties:
      amount:
        type: integer
        docs: The amount (in cents) of the credit line offer (e.g. '200000' for
          $2,000.00)
      apr:
        type: optional<integer>
        docs: The annual percentage rate (in basis points) of the credit line
      annual_fee:
        type: optional<integer>
        docs: The annual fee charged for the credit line (e.g. '5000' for $50.00)
      billing_cycle:
        type: optional<integer>
        docs: >
          The time in days between the last statement's closing date and the next statement's closing date. 
          For consumer lines of credit, the minimum is '21'
      finance_charge:
        type: optional<integer>
        docs: >
          If your platform charges a monthly finance charge for access to the line,
          the amount in cents
      grace_period: optional<GracePeriod>
      interest_rate:
        type: optional<integer>
        docs: >
          The interest rate (in basis points) of the loan or credit line offer (e.g.
          '750' for 7.50%)
      late_payment_fee:
        type: optional<integer>
        docs: >
          The fee charged if a borrower misses the payment due date, in cents (e.g.
          '2500' for $25.00; default to 0)
      minimum_payment:
        type: optional<MinimumPayment>
        docs: The minimum payment due each billing cycle
      origination_fee:
        type: optional<integer>
        docs: >
          The origination fee charged to originate the line in basis points (e.g. '150'
          for 1.50%)

  LoanOffer:
    properties:
      amount:
        type: integer
        docs: The amount (in cents) of the loan offer (e.g. 200000 for $2,000.00)
      grace_period: optional<GracePeriod>
      interest_rate:
        type: optional<integer>
        docs: The interest rate (in basis points) charged on the loan principal (e.g. 750 for 7.50%)
      origination_fee:
        type: optional<integer>
        docs: The origination fee charged to originate the loan in basis points (e.g. 150 for 1.50%)
      payment_period:
        type: optional<RepaymentFrequency>
        docs: The repayment frequency for the loan. Accepted values weekly, biweekly, monthly, semi_monthly_first_15th, semi_monthly_last_15th, semi_monthly
      first_payment_date:
        type: optional<string>
        docs: The date of the first payment, in ISO 8601 format (e.g. 2022-12-31)
      late_payment_fee:
        type: optional<integer>
        docs: The fee charged if a borrower misses the payment due date, in cents (e.g. 2500 for $25.00)
      term:
        type: Term
        docs: The type of term. Accepted values are months, days, payments
      security_amount:
        type: optional<integer>
        docs: The amount (in cents) of the value of the loan collateral (e.g. 200000 for $2,000.00). Required for secured loan application types.

  MerchantAdvanceOfferSchema:
    properties:
      amount:
        type: integer
        docs: The amount (in cents) of the loan offer (e.g. 200000 for $2,000.00)
      factor_rate:
        type: integer
        docs: The cost of the merchant advance (in basis points) and will be multiplied by the loan amount (e.g. 150 for 1.50%)
      payment_period:
        type: optional<RepaymentFrequency>
        docs: The repayment frequency for the loan. Accepted values weekly, biweekly, monthly, semi_monthly_first_15th, semi_monthly_last_15th, semi_monthly
      origination_fee:
        type: optional<integer>
        docs: >
          The origination fee charged to originate the line in basis points (e.g. '150'
          for 1.50%)
      late_payment_fee:
        type: optional<integer>
        docs: The fee charged if a borrower misses the payment due date, in cents (e.g. 2500 for $25.00)
      receivables_portion:
        type: optional<integer>
        docs: The portion collected from each sale until the advance is repayed
      minimum_payment:
        type: optional<integer>
        docs: The minimum payment due each billing cycle
      maximum_payment:
        type: optional<integer>
        docs: The minimum payment due each billing cycle

  GracePeriod:
    properties:
      term:
        type: optional<integer>
        docs: The time in days between the end of a billing cycle and the bill's due date. For consumer lines of credit, the minimum is '21'
      interest_rate:
        type: optional<integer>
        docs: The interest rate (in basis points) charged during the grace period. Must be '0' for consumer lines of credit. Defaults to 0 if omitted

  Term:
    properties:
      term_type: TermType
      term:
        type: integer
        docs: The term of the loan according to the term type. A minimum of 3 is required for monthly payment_period, 6 for semi-monthly, 7 for biweekly and 13 for weekly.

  RepaymentFrequency:
    enum:
      - value: weekly
        docs: Weekly payment period
      - value: biweekly
        docs: Biweekly payment period
      - value: monthly
        docs: Monthly payment period
      - value: semi_monthly_first_15th
        docs: Semi-monthly payment period, with payments due on the 1st and 15th of each month
      - value: semi_monthly_last_15th
        docs: Semi-monthly payment period, with payments due on the 15th and last day of each month
      - value: semi_monthly
        docs: Semi-monthly payment period

  MinimumPayment:
    properties:
      type:
        type: MinimumPaymentType
        docs: The type of minimum payment structure. Accepted values are interest_plus_percentage_of_principal
      value:
        type: integer
        docs: The minimum payment percentage due each billing cycle (e.g. 500 for 5.00%)

  MinimumPaymentType:
    enum:
      - value: interest_plus_percentage_of_principal
        docs: |
          The minimum payment is 100% of interest accrued plus a percentage of the principal balance

  RejectionReason:
    enum:
      - value: income_too_low
        docs: Income does not meet requirement
      - value: bank_balance_too_low
        docs: Bank account balance is too low
      - value: income_unpredictable
        docs: Unable to predict regular pattern of income deposits
      - value: user_account_duplicate
        docs:
          Duplicate account (previously applied for a loan with a different email
          address)
      - value: sdb_check_failed
        docs: State database lending restriction
      - value: bank_account_linking_error
        docs: Unable to link to a supported banking institution
      - value: mla_failed
        docs: |
          Under the Military Lending Act, loans to military personnel or their spouses
          and dependents cannot be made if the interest and expenses associated with the
          loan exceed an annual percentage rate (APR) of 36%. Due to these limits on
          military-related lending, we can't lend to members of the military or their
          spouses and dependents. Please feel free to contact us with any questions you
          may have about this notice!
      - value: iddoc_failed
        docs: Unable to verify identification documents
      - value: no_checking_or_savings_data
        docs:
          No data from supported financial institution. Unsupported financial
          institution is linked
      - value: insufficient_bank_history
        docs: Unable to pull enough bank history
      - value: loan_location_no_license
        docs: Unable to verify that your permanent residence is in a state
      - value: address_invalid
        docs: Unable to verify mailing address
      - value: income_verification_failed
        docs: Unable to verify qualified income over a sustained period
      - value: stacking_behavior
        docs: Recent deposits and withdrawals detected from other lenders
      - value: ssn_verification_failed
        docs: Unable to verify SSN number
      - value: too_many_nsfs
        docs: Multiple Returned checks or Insufficient Fund Fees detected
      - value: fraud_risk_too_high
        docs: Bank account has been flagged as potential fraud risk
      - value: has_bankruptcy_history
        docs: History of bankruptcy
      - value: unable_to_verify_credit_information
        docs: Unable to verify credit information
      - value: credit_file_frozen
        docs: Credit file is currently frozen
      - value: processor_suspended
        docs: Payment processor is unable to authenticate user
      - value: cash_flow_verification_failed
        docs:
          Cash flow analysis - income funds are quickly depleted from bank account
          after income deposit
      - value: credit_score_too_low
        docs: Your credit score does not meet our requirement

  GetApplicationRequest:
    properties:
      application_id:
        type: string
        docs: The id of the borrower you're requesting to retrieve

  TermType:
    enum:
      - value: months
        docs: The term of the line is in months
      - value: days
        docs: The term of the line is in days
      - value: payments
        docs: The term of the line is in number of payments

  CreditData:
    properties:
      fico:
        type: optional<integer>
        docs: A FICO score (e.g. 750)
      has_bankruptcy_history:
        type: optional<boolean>
        docs: Whether or not there is bankruptcy history
