# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

docs: >
  Webhook, lending details and other various system configurations can be set and retrieved using the Configuration API.

imports:
  commons: commons.yml

service:
  base-path: /configuration
  auth: true
  endpoints:
    set_webhook_urls:
      display-name: Set webhook URLs
      docs: Set the array of urls to receive webhook events from Pier.
      path: "/webhook"
      method: POST
      request:
        name: SetWebhook
        body:
          properties:
            urls:
              type: list<string>
              docs: The array of `urls` to send webhooks to
      response: WebhookUrls
      errors:
        - commons.InvalidWebhookError
      examples:
        - request:
            urls:
              - "https://example.com/webhook1"
              - "https://example.com/webhook2"
          response:
            body: $WebhookUrls.Default

    delete_webhook_urls:
      display-name: Reset webhook URLs
      docs: Reset the array of `urls` that receives Pier webhooks.
      path: "/webhook"
      method: DELETE
      response: DeleteWebhookResponse
      examples:
        - response:
            body: $DeleteWebhookResponse.Default

    get_webhook_urls:
      display-name: Get webhook URLs
      docs: Get the array of `urls` that receives Pier webhooks.
      path: "/webhook"
      method: GET
      response: WebhookUrls
      examples:
        - response:
            body: $WebhookUrls.Default

    webhook_verification:
      display-name: Verify a webhook with Pier public key
      docs: The Pier public key to use to verify webhook signatures.
      path: "/webhook-verification"
      method: GET
      response: VerificationResponse
      examples:
        - response:
            body:
              public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ\njkdfhdfjskfhsd==\n-----END PUBLIC KEY-----"

    set_lending_details:
      display-name: Set lending details
      docs: Only valid in Starter Mode
      path: "/lending_details"
      method: POST
      request:
        name: SetLendingDetailsRequest
        body: LendingDetails
      response:
        type: LendingDetails
      errors:
        - commons.InvalidLendingDetailsError
      examples:
        - request: $LendingDetails.Default
          response:
            body: $LendingDetails.Default

    delete_lending_details:
      display-name: Remove lending details
      docs: Only valid when lending through Pier.
      path: "/lending_details"
      method: DELETE
      response: string
      errors:
        - commons.InvalidLendingDetailsError
      examples:
        - request:
          response:
            body: Ok.

types:
  WebhookUrls:
    properties:
      urls:
        type: list<string>
        docs: The array of `urls` to send webhooks to
    examples:
      - name: Default
        value:
          urls:
            - "https://example.com/webhook1"
            - "https://example.com/webhook2"

  DeleteWebhookResponse:
    properties:
      urls: list<string>
    examples:
      - name: Default
        value:
          urls: []

  VerificationResponse:
    properties:
        public_key:
            type: string
            docs: The `public_key` to use to verify Pier webhook signatures
  LendingDetails:
    properties:
      address:
        type: commons.Address
        docs: Your address as lender of record
      cs_phone:
        type: string
        docs: Your customer service phone number
      cs_email:
        type: string
        docs: Your customer service email
    examples:
      - name: Default
        value:
          address:
            line_1: "123 Main St"
            line_2: "Suite 100"
            city: "San Francisco"
            state: "CA"
            zip: "94105"
          cs_phone: "415-555-5555"
          cs_email: "support@example.com"
