# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

docs: |
  Webhooks

imports:
  commons: commons.yml

service:
  base-path: /configuration
  auth: true
  endpoints:
    create:
      display-name: Set webhook URL
      path: "/webhook"
      method: POST
      request:
        name: CreateWebhookRequest
        body:
          properties:
            url:
              type: string
              docs: The `url` to send webhooks to
      response: string
      errors:
        - commons.InvalidWebhookError
      examples:
        - request:
            url: "https://example.com/webhook"
          response:
            body: Ok.

    delete:
      display-name: Remove a webhook
      path: "/webhook"
      method: DELETE
      response: string
      examples:
        - request:
          response:
            body: Ok.

    verification:
      display-name: Verify a webhook with Pier public key
      path: "/webhook-verification"
      method: GET
      response:
        body:
          properties:
            public_key:
              type: string
              docs: The `public_key` to use to verify Pier webhook signatures
      examples:
        - response:
            body:
              public_key: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ\njkdfhdfjskfhsd==\n-----END PUBLIC KEY-----"
