name: pr

on:
  pull_request:
    branches: [main]

jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Fern
        run:  npm install -g fern-api

      - name: Generate docs
        id: generate
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate

      - name: Check Fern API is valid
        if: steps.generate.outcome == 'success'
        run: fern check
