name: push

on:
  push:
    branches: [main]

jobs:
  fern-generate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Fern
        run:  npm install -g fern-api

      - name: Generate docs
        id: generate-docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs

      - name: Generate OpenAPI
        id: generate
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate

      - name: Run `openapi` command 🚀
        if: steps.generate.outcome == 'success'
        uses: readmeio/rdme@v8
        with:
          rdme: openapi openapi/openapi.yml --key=${{ secrets.README_API_KEY }} --id=64681e7578f3e900117d08bc

      - name: PR OpenAPI docs
        run: |
          git clone https://${{secrets.OPENAPI_REPO_PAT}}@github.com/pierdeveloper/pierapi-openapi.git
          cd pierapi-openapi
          git config user.email "mike.jannain@pier-finance.com"
          git config user.name "MJ"
          git checkout -b docsupdate-${{ github.run_id }}-${{ github.run_attempt }}
          rm openapi.yml -f
          cp ../openapi/openapi.yml .
          git add .
          git commit -m "Update OpenAPI docs from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
          gh pr create --title "Update OpenAPI docs from ${GITHUB_REPOSITORY}@${GITHUB_SHA}" --body "Update OpenAPI docs from ${GITHUB_REPOSITORY}@${GITHUB_SHA}" --head "docsupdate-${{ github.run_id }}-${{ github.run_attempt }}" --base main
          gh pr merge --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
